---
- hosts: all
  become: true
  vars:
     home_server_tools: "/home/lpena/Documents/Tools"
     bin_path: "/usr/local/bin"
     distro_kernel: $(uname -s)
     architecture_server: $(uname -m)
     download_compose_directory: "/home/ubuntu/docker-compose-Linux-x86_64"
     download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
     download_url_jenkins: http://mirrors.jenkins.io/war/latest/jenkins.war
     download_url_maven: http://www-eu.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
     download_folder: /opt
     tomcat_folder: "{{download_folder}}/apache-tomcat-8.5.23"
     wildfly_folder: "{{download_folder}}/wildfly-11.0.0.Final"
     tomcat: "apache-tomcat-8.5.23.tar.gz"
     wildfly: "wildfly-11.0.0.Final.tar.gz"
     sonar: "{{download_folder}}/sonarqube-6.6"
     sonarcube: "sonarqube-6.6.zip"
     sonar_compose_file: "docker-compose.yml"
     sonar_compose_file_dest: "{{download_folder}}/{{sonar_compose_file}}"
     java_name: "{{download_folder}}/jdk1.8.0_151"
     jenkins_name: "{{download_folder}}/jenkins.war"
     sonarcube_name: "{{download_folder}}/{{sonarcube}}"
     tomcat_name: "{{download_folder}}/{{tomcat}}"
     wildfly_name: "{{download_folder}}/{{wildfly}}"
     maven: apache-maven-3.5.0-bin.tar.gz
     maven_name: "{{download_folder}}/apache-maven-3.5.0"
     maven_archive: "{{download_folder}}/apache-maven-3.5.0-bin.tar.gz"
     java_archive: "{{download_folder}}/jdk-8u151-linux-x64.tar.gz"
     jenkins_archive: "{{download_folder}}/{{download_url_jenkins}}"
     maven_archive: "{{download_folder}}/{{download_url_maven}}"
     java_package_name: jdk-8u151-linux-x64.tar
     tomcat_deployments: "/opt/apache-tomcat-8.5.23/webapps"
     wildfly_deployments: "/opt/wildfly-11.0.0.Final/standalone/deployments"
     jenkins_service: "/home/lpena/Documents/DevOps/vagrant-test/jenkins.service"
     tomcat_service: "/home/lpena/Documents/DevOps/vagrant-test/tomcat.service"
     tomcat_conf: "/home/lpena/Documents/DevOps/vagrant-test/server.xml"
     path: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ubuntu/.local/bin:/home/ubuntu/bin
  tasks:

##Update system ready 
    - name: update
      command: apt-get update
      become_user: root

    - name: upgrade
      command: apt-get -y upgrade
      become_user: root

    - name: install pip
      command: sudo apt-get install -y python3-pip
      become_user: root

    - name: create sonar paths /opt/sonarqube
      command: "mkdir -p /opt/sonarqube"
      become_user: root

    - name: create sonar paths /opt/sonarqube/conf
      command: "mkdir -p /opt/sonarqube/conf"
      become_user: root

    - name: create sonar paths /opt/sonarqube/data
      command: "mkdir -p /opt/sonarqube/data"
      become_user: root
    
    - name: create /opt/sonarqube/extensions
      command: "mkdir -p /opt/sonarqube/extensions"
      become_user: root

    - name: create /opt/sonarqube/lib
      command: "mkdir -p /opt/sonarqube/lib"
      become_user: root

    - name: create /opt/sonarqube/lib/bundled-plugins
      command: "mkdir -p /opt/sonarqube/lib/bundled-plugins"
      become_user: root

    - name: install upstart
      apt: name=upstart update_cache=yes state=latest

##Postgres ready
    - name: ensure postgresql is at the latest version
      apt: name=postgresql state=latest

    - name: ensure that postgresql is started
      service: name=postgresql state=started

##Docker 
    - name: install docker
      apt: name=docker state=latest

##Docker compose 
    - name: install compose
      apt: name=docker-compose state=latest

    - name: ensure docker-compose installation
      command: docker-compose -v

##Sonarqube
    - name: Sonarcube (docker virtual environment)
      command: cd /opt
      command: docker-compose up

##Java ready     
    - name: install open-jdk 8
      command: apt-get install openjdk-8-jre --assume-yes
      sudo: yes

##Jenkins download ready
    - name: Download Jenkins
      get_url:
        url:  "{{download_url_jenkins}}"
        dest: "{{jenkins_name}}"
        mode: 0440
      sudo: yes
    
    - name: Change jenkins archive privileges
      command: "chmod 775 {{jenkins_name}}"
      sudo: yes

##Copy wildfly and jenkins deployment ready    
    - copy:
        src: "{{home_server_tools}}/{{wildfly}}"
        dest: "{{wildfly_name}}"
        mode: 0644
      sudo: yes
    
    - name: Change wildfly archive privileges
      command: "chmod 775 {{wildfly_name}}"
      sudo: yes         
    
    - name: extract wildfly
      command: tar zxvf {{wildfly_name}}
      sudo: yes
    
    - name: copy wildfly to opt
      shell: "cp -R /home/ubuntu/wildfly-11.0.0.Final {{wildfly_folder}}"
      sudo: yes
    
    - name: copy jenkins to deployments
      command: cp {{jenkins_name}} {{wildfly_deployments}}
      sudo: yes
    
    - name: start wildfly and deploy jenkins
      shell: "{{wildfly_folder}}/bin/standalone.sh &"
      sudo: yes
  
##Copy tomcat      
    - copy:
        src: "{{home_server_tools}}/{{tomcat}}"
        dest: "{{tomcat_name}}"
        mode: 0644
      sudo: yes
    
    - name: Change tomcat archive privileges
      command: "chmod 775 {{tomcat_name}}"
      sudo: yes         
    
    - name: extract tomcat
      command: tar zxvf {{tomcat_name}}
      sudo: yes
    
    - name: copy tomcat to opt
      shell: "cp -R /home/ubuntu/apache-tomcat-8.5.23 {{tomcat_folder}}"
      sudo: yes
    
    - copy:
        src: "{{tomcat_conf}}"
        dest: "{{tomcat_folder}}/conf"
        mode: 0644
      sudo: yes
    
    - name: copy jenkins to tomcat deployments
      command: cp {{jenkins_name}} {{tomcat_deployments}}
      sudo: yes
    
    - name: start tomcat
      shell: "nohup {{tomcat_folder}}/bin/catalina.sh start"
      sudo: yes 

##Jenkins service 
    - copy:
        src: "{{jenkins_service}}"
        dest: /etc/systemd/system/jenkins.service
        mode: 0644
      sudo: yes
    
    - name: start jenkins service
      shell: systemctl start jenkins.service
      sudo: yes 

##Maven ready
    - name: install maven
      command: sudo apt-get install maven --assume-yes
      sudo: yes
    
    - name: verify maven was installed
      command: mvn -version      

##Apache2 ready   
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      sudo: yes 
    
    - name: ensure apache is running (and enable it at boot)
      service: name=apache2 state=started enabled=yes

